SUPABASE_URL = "https://pbdtojwwhtqojqhrwjia.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZHRvand3aHRxb2pxaHJ3amlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNDQ3ODUsImV4cCI6MjA4ODgyMDc4NX0.HdBOD96N8c0Sdi8pmw-zAIM_0gNZUSwD7MiIdybay-0
